# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import worker_control_pb2 as worker__control__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in worker_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadShard = channel.unary_unary(
                '/loom.control.v0.WorkerControl/LoadShard',
                request_serializer=worker__control__pb2.LoadShardRequest.SerializeToString,
                response_deserializer=worker__control__pb2.Ack.FromString,
                _registered_method=True)
        self.UnloadShard = channel.unary_unary(
                '/loom.control.v0.WorkerControl/UnloadShard',
                request_serializer=worker__control__pb2.UnloadShardRequest.SerializeToString,
                response_deserializer=worker__control__pb2.Ack.FromString,
                _registered_method=True)
        self.SetQuota = channel.unary_unary(
                '/loom.control.v0.WorkerControl/SetQuota',
                request_serializer=worker__control__pb2.QuotaRequest.SerializeToString,
                response_deserializer=worker__control__pb2.Ack.FromString,
                _registered_method=True)
        self.StartServing = channel.unary_unary(
                '/loom.control.v0.WorkerControl/StartServing',
                request_serializer=worker__control__pb2.ModelRequest.SerializeToString,
                response_deserializer=worker__control__pb2.Ack.FromString,
                _registered_method=True)
        self.StopServing = channel.unary_unary(
                '/loom.control.v0.WorkerControl/StopServing',
                request_serializer=worker__control__pb2.ModelRequest.SerializeToString,
                response_deserializer=worker__control__pb2.Ack.FromString,
                _registered_method=True)
        self.ReportTelemetry = channel.unary_unary(
                '/loom.control.v0.WorkerControl/ReportTelemetry',
                request_serializer=worker__control__pb2.TelemetryRequest.SerializeToString,
                response_deserializer=worker__control__pb2.TelemetryReport.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/loom.control.v0.WorkerControl/Heartbeat',
                request_serializer=worker__control__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=worker__control__pb2.HeartbeatAck.FromString,
                _registered_method=True)


class WorkerControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LoadShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetQuota(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartServing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopServing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadShard': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadShard,
                    request_deserializer=worker__control__pb2.LoadShardRequest.FromString,
                    response_serializer=worker__control__pb2.Ack.SerializeToString,
            ),
            'UnloadShard': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadShard,
                    request_deserializer=worker__control__pb2.UnloadShardRequest.FromString,
                    response_serializer=worker__control__pb2.Ack.SerializeToString,
            ),
            'SetQuota': grpc.unary_unary_rpc_method_handler(
                    servicer.SetQuota,
                    request_deserializer=worker__control__pb2.QuotaRequest.FromString,
                    response_serializer=worker__control__pb2.Ack.SerializeToString,
            ),
            'StartServing': grpc.unary_unary_rpc_method_handler(
                    servicer.StartServing,
                    request_deserializer=worker__control__pb2.ModelRequest.FromString,
                    response_serializer=worker__control__pb2.Ack.SerializeToString,
            ),
            'StopServing': grpc.unary_unary_rpc_method_handler(
                    servicer.StopServing,
                    request_deserializer=worker__control__pb2.ModelRequest.FromString,
                    response_serializer=worker__control__pb2.Ack.SerializeToString,
            ),
            'ReportTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTelemetry,
                    request_deserializer=worker__control__pb2.TelemetryRequest.FromString,
                    response_serializer=worker__control__pb2.TelemetryReport.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=worker__control__pb2.HeartbeatRequest.FromString,
                    response_serializer=worker__control__pb2.HeartbeatAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loom.control.v0.WorkerControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loom.control.v0.WorkerControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LoadShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loom.control.v0.WorkerControl/LoadShard',
            worker__control__pb2.LoadShardRequest.SerializeToString,
            worker__control__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loom.control.v0.WorkerControl/UnloadShard',
            worker__control__pb2.UnloadShardRequest.SerializeToString,
            worker__control__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetQuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loom.control.v0.WorkerControl/SetQuota',
            worker__control__pb2.QuotaRequest.SerializeToString,
            worker__control__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartServing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loom.control.v0.WorkerControl/StartServing',
            worker__control__pb2.ModelRequest.SerializeToString,
            worker__control__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopServing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loom.control.v0.WorkerControl/StopServing',
            worker__control__pb2.ModelRequest.SerializeToString,
            worker__control__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loom.control.v0.WorkerControl/ReportTelemetry',
            worker__control__pb2.TelemetryRequest.SerializeToString,
            worker__control__pb2.TelemetryReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loom.control.v0.WorkerControl/Heartbeat',
            worker__control__pb2.HeartbeatRequest.SerializeToString,
            worker__control__pb2.HeartbeatAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
